version: '3.4'

services:
  users-service:
    build: ./src/Services/UsersService
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=marketplace_db;Username=marketplace;Password=marketplace_password;Search Path=users_service;
    depends_on:
      - postgres-db

  nginx-gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users-service

  postgres-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace_password
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: