version: '3.8'

services:
  users-service:
    build: ./src/Services/UsersService
    container_name: users-service
    ports:
      - "5002:80"  # Змінив порт, щоб не конфліктувати з files-service
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=marketplace_db;Username=marketplace;Password=marketplace_password;Search Path=users_service;
    depends_on:
      - postgres-db
    networks:
      - app-network

  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - users-service
    #   - products-service
    #   - files-service
    networks:
      - app-network

  products-service:
    build:
      context: ./src/Services/ProductsService
    container_name: products-service
    ports:
      - "5003:80"  # Змінив порт для унікальності
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=marketplace_db;Username=marketplace;Password=marketplace_password;Search Path=products_service;  # Виправив схему
    depends_on:
      - postgres-db
    networks:
      - app-network

  files-service:
    build:
      context: ./src/Services/FilesService
      dockerfile: Dockerfile
    container_name: files-service
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=minioadmin
      - MinIO__SecretKey=minioadmin123
      - MinIO__BucketName=images
      - MinIO__Secure=false
    depends_on:
      - minio
    networks:
      - app-network

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace_password
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
      
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # API порт
      - "9001:9001"     # Console порт
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
  postgres_data:

networks:
  app-network:
    driver: bridge