"""init

Revision ID: dd3b4b618c7c
Revises: 
Create Date: 2025-07-16 21:22:18.901565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3b4b618c7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('min_order_amount', sa.Float(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='orders_service'
    )
    op.create_index(op.f('ix_orders_service_promo_codes_code'), 'promo_codes', ['code'], unique=True, schema='orders_service')
    op.create_index(op.f('ix_orders_service_promo_codes_id'), 'promo_codes', ['id'], unique=False, schema='orders_service')
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='orders_service'
    )
    op.create_index(op.f('ix_orders_service_statuses_id'), 'statuses', ['id'], unique=False, schema='orders_service')
    op.create_index(op.f('ix_orders_service_statuses_name'), 'statuses', ['name'], unique=True, schema='orders_service')
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['orders_service.statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders_service'
    )
    op.create_index(op.f('ix_orders_service_orders_id'), 'orders', ['id'], unique=False, schema='orders_service')
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders_service.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders_service'
    )
    op.create_index(op.f('ix_orders_service_order_items_id'), 'order_items', ['id'], unique=False, schema='orders_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_service_order_items_id'), table_name='order_items', schema='orders_service')
    op.drop_table('order_items', schema='orders_service')
    op.drop_index(op.f('ix_orders_service_orders_id'), table_name='orders', schema='orders_service')
    op.drop_table('orders', schema='orders_service')
    op.drop_index(op.f('ix_orders_service_statuses_name'), table_name='statuses', schema='orders_service')
    op.drop_index(op.f('ix_orders_service_statuses_id'), table_name='statuses', schema='orders_service')
    op.drop_table('statuses', schema='orders_service')
    op.drop_index(op.f('ix_orders_service_promo_codes_id'), table_name='promo_codes', schema='orders_service')
    op.drop_index(op.f('ix_orders_service_promo_codes_code'), table_name='promo_codes', schema='orders_service')
    op.drop_table('promo_codes', schema='orders_service')
    # ### end Alembic commands ###